services:
  etendo_ui:
    container_name: etendo_ui
    image: etendo/etendo_ui:${UI_VERSION:-latest}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - etendo
    environment:
      - ETENDO_CLASSIC_URL=${ETENDO_CLASSIC_URL}
      - ETENDO_CLASSIC_HOST=${ETENDO_CLASSIC_HOST}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  etendo:
    external: true