image: maven:3.8.4

clone:
  depth: full

definitions:
  services:
    docker:
      memory: 1024
    docker-more-memory:
      memory: 2048
      type: docker
  steps:
    - step: &git-police
        name: Git Police Step
        script:
          - printenv
          - echo "-------------------------------------------------------------------------"
          - echo "${DOCKERHUB_PASSWORD}" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          - docker run -d -p 5000:5000 -e REPO_TOKEN="${ETENDOBOT_TOKEN}" -e PR_ID="$BITBUCKET_PR_ID" -e REPO_NAME="$BITBUCKET_REPO_SLUG" etendo/gitpolice:"${GITPOLICE_VERSION}"
          - echo "-------------------------------------------------------------------------"
          - sleep 10s
          - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/api/bitbucket)
          - |
            if [ "$response" -ne 200 ]; then
              echo "API call failed with status code $response"
              cat response.txt
              exit 1
            fi
          - |
            if ! grep -q "Valid branch name and correct destination" response.txt; then
              echo "Git Police check failed: response does not contain 'Valid branch name and correct destination'"
              echo "Full response:"
              cat response.txt
              exit 1
            fi
          - echo "API call successful with status code $response"
          - cat response.txt
        services:
          - docker

    - step: &make-review
        name: Make Review Step
        script:
          - printenv
          - echo "-------------------------------------------------------------------------"
          - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
          - docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST="${BITBUCKET_PR_ID}" -e PROJECT="${BITBUCKET_REPO_OWNER}" -e REPO_SLUG="${BITBUCKET_REPO_SLUG}" -e OPENAI_API_KEY="${OPENAI_API_KEY}" etendo/code-reviewer:"${REVIEWER_VERSION}"
          - echo "-------------------------------------------------------------------------"
          - sleep 10s
          - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/bitbucket)
          - |
            if [ "$response" -ne 200 ]; then
              echo "API call failed with status code $response"
              cat response.txt
              exit 1
            fi
          - echo "API call successful with status code $response"
          - cat response.txt
        services:
          - docker

    - step: &build-step
        name: SonarQube analysis
        script:
          - pipe: sonarsource/sonarqube-scan:3.1.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL} # Get the value from the repository/workspace variable.
              SONAR_TOKEN: ${SONAR_TOKEN} # Get the value from the repository/workspace variable. You shouldn't set secret in clear text here.
              SONAR_EXCLUDE: node_modules, android, ios
        services:
          - docker-more-memory
  caches:
    sonar: ~/.sonar

pipelines:
  branches:
    '{master,main,develop,release/*}':
      - step: *build-step
  pull-requests:
    'develop':
      - step:
          script:
            - echo "Skip for develop branch"
            - exit 0
    '**':
      - step: *git-police
      - parallel:
          - step: *make-review
          - step: *build-step
